kind: Service
apiVersion: v1
metadata:
  name: susi-slackbot
  namespace: slack
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: susi-slackbot
  type: LoadBalancer 