kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: susi-slackbot
  namespace: slackbot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: susi-slackbot
    spec:
      containers:
      - name: susi-slackbot
        image: aliayubkhan/susi_slackbot:latest-development
        env:
        - name: slackToken
          value: "xoxb-231825183429-3VqJmUKux6YsJiq9e3Mcl9tZ"
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: susi-slackbot
      restartPolicy: Always
