kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: susi-slackbot
  namespace: slackbot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: susi-slackbot
    spec:
      containers:
      - name: susi-slackbot
        image: aliayubkhan/susi_slackbot:latest
        env:
        - name: X_VIBER_AUTH_TOKEN
          value: "45a53f0fcb325002-41552d1f93cd0d0f-1a8d7fa78758d158"
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: susi-slackbot
      restartPolicy: Always
