kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: slack
  namespace: slack
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: slack
    spec:
      containers:
      - name: slack
        image: aliayubkhan/susi_slackbot:latest
        env:
        - name: slackToken
          value: "xoxb-185920210817-emzvFPZLXIVEIRcGMeFIagW9"
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: slack
      restartPolicy: Always
